# Generated by Django 4.2.16 on 2025-03-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'TXT'), ('doc', 'DOC'), ('ipynb', 'IPYNB')], max_length=10),
        ),
    ]
